In [1]:
import numpy as np
import pandas as pd
import scipy.stats as stat
import scipy.io as scipio
import matplotlib.pyplot as plt
%matplotlib inline
import datetime

In [2]:
data_train = pd.DataFrame(pd.read_csv("data_train.csv"))
data_test = pd.DataFrame(pd.read_csv("data_test.csv"))

In [3]:
data_test = data_test.dropna(0)

In [4]:
# data_test["air_store_id"].value_counts()

In [5]:
len(data_test)

30725

In [6]:
len(data_train)

173703

In [7]:
data_train = data_train.sort_values(by="visit_date", ascending=True)

In [8]:
data_train = data_train.dropna(0)

data_test.to_csv("data_test.csv")
data_train.to_csv("data_train.csv")

In [ ]:
## Just to See How This Works

In [28]:
data_train.head()

,air_store_id,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday,avg_temperature1,high_temperature1,...,Ōsaka-fu Neyagawa-shi Honmachi,Ōsaka-fu Sakai-shi Minamikawaramachi,Ōsaka-fu Suita-shi Izumichō,Ōsaka-fu Ōsaka-shi Fuminosato,Ōsaka-fu Ōsaka-shi Kyōmachibori,Ōsaka-fu Ōsaka-shi Kyūtarōmachi,Ōsaka-fu Ōsaka-shi Nakanochō,Ōsaka-fu Ōsaka-shi Nanbasennichimae,Ōsaka-fu Ōsaka-shi Shinmachi,Ōsaka-fu Ōsaka-shi Ōgimachi
36066,air_a083834e7ffe187e,1,0,0,0,0,0,0,2.4,6.1,...,0,0,0,0,0,0,0,0,0,0
4491,air_36bcf77d3382d36e,1,0,0,0,0,0,0,7.5,12.1,...,0,0,0,0,0,0,0,0,0,0
193412,air_cb7467aed805e7fe,1,0,0,0,0,0,0,7.3,12.6,...,0,0,0,0,0,0,0,0,0,0
192565,air_35c4732dcbfe31be,1,0,0,0,0,0,0,7.9,12.3,...,0,0,0,0,0,0,0,0,0,0
100233,air_6e3fd96320d24324,1,0,0,0,0,0,0,4.7,12.1,...,0,0,0,0,0,0,0,0,0,0

In [36]:
# print (*enumerate(list(data_train.columns.values)))

In [108]:
train_exog_cols = np.where((data_train.columns.values != "visitors") & (data_train.columns.values != "train_ind") &\
         (data_train.columns.values != "visit_date") & (data_train.columns.values != "air_store_id"))         

# train_exog_cols = np.where((data_train.columns.values != "train_ind") &\
#          (data_train.columns.values != "visit_date") & (data_train.columns.values != "air_store_id"))

In [124]:
data_train = data_train.set_index("visit_date",drop=True)

In [272]:
# data_train

In [127]:
train_exog_cols = np.where((data_train.columns.values != "visitors") & (data_train.columns.values != "train_ind") &\
         (data_train.columns.values != "visit_date") & (data_train.columns.values != "air_store_id"))         

# train_exog_cols = np.where((data_train.columns.values != "train_ind") &\
#          (data_train.columns.values != "visit_date") & (data_train.columns.values != "air_store_id"))

In [128]:
data_train[data_train.columns[train_exog_cols]].shape

(173703, 128)

In [271]:
# data_train

In [131]:
arima_visitors_endo = pd.DataFrame(data_train["visitors"], index=data_train.index)
arima_exog = [data_train[data_train.columns[train_exog_cols]]][0]
arima_dates = data_train.index

In [132]:
from statsmodels.tsa.arima_model import ARIMA
# arima_model = ARIMA(endog=a)

In [133]:
from statsmodels.tsa.stattools import adfuller
from sklearn.preprocessing import StandardScaler

In [135]:
adfuller(arima_visitors_endo["visitors"])

(-21.295299482775626,
 0.0,
 78,
 173624,
 {'1%': -3.4303876641287081,
  '10%': -2.5667788606193764,
  '5%': -2.8615566470325957},
 1459947.8049465078)

In [137]:
scaler = StandardScaler()
arima_visitors_endo = scaler.fit_transform(arima_visitors_endo)

In [138]:
arima_exog["avg_temperature1"] = scaler.fit_transform(arima_exog["avg_temperature1"].reshape(-1,1))
arima_exog["low_temperature1"] = scaler.fit_transform(arima_exog["low_temperature1"].reshape(-1,1))
arima_exog["high_temperature1"] = scaler.fit_transform(arima_exog["high_temperature1"].reshape(-1,1))
arima_exog["hours_sunlight1"] = scaler.fit_transform(arima_exog["hours_sunlight1"].reshape(-1,1))

/Users/derin/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning:

reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead

/Users/derin/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/derin/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning:

reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead

/Users/derin/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/derin/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning:

reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead

/Users/derin/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/derin/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:4: FutureWarning:

reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead

/Users/derin/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [139]:
arima_visitors_endo

array([[ 0.36549553],
       [ 0.78871241],
       [ 0.72825286],
       ...,
       [ 1.87698438],
       [-0.9041551 ],
       [ 1.27238884]])

In [140]:
np.array(arima_exog)

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.]])

In [141]:
from datetime import datetime

In [151]:
arima_dates = pd.Series(data_train.index.values).apply(lambda x: datetime.strptime(x, "%Y-%m-%d"))

In [152]:
arima_dates[0]

Timestamp('2016-01-01 00:00:00')

In [153]:
len(arima_dates)

173703

In [ ]:
area_names = are

In [187]:
arima_exog

,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday,avg_temperature1,high_temperature1,holiday_flg,...,Ōsaka-fu Neyagawa-shi Honmachi,Ōsaka-fu Sakai-shi Minamikawaramachi,Ōsaka-fu Suita-shi Izumichō,Ōsaka-fu Ōsaka-shi Fuminosato,Ōsaka-fu Ōsaka-shi Kyōmachibori,Ōsaka-fu Ōsaka-shi Kyūtarōmachi,Ōsaka-fu Ōsaka-shi Nakanochō,Ōsaka-fu Ōsaka-shi Nanbasennichimae,Ōsaka-fu Ōsaka-shi Shinmachi,Ōsaka-fu Ōsaka-shi Ōgimachi
visit_date,,,,,,,,,,,,,,,,,,,,,
2016-01-01,1,0,0,0,0,0,0,-1.453833,-1.493155,1.0,...,0,0,0,0,0,0,0,0,0,0
2016-01-01,1,0,0,0,0,0,0,-0.885074,-0.837613,1.0,...,0,0,0,0,0,0,0,0,0,0
2016-01-01,1,0,0,0,0,0,0,-0.907378,-0.782984,1.0,...,0,0,0,0,0,0,0,0,0,0
2016-01-01,1,0,0,0,0,0,0,-0.840465,-0.815761,1.0,...,0,0,0,0,0,0,0,0,0,0
2016-01-01,1,0,0,0,0,0,0,-1.197334,-0.837613,1.0,...,0,0,0,0,0,0,0,0,0,0
2016-01-01,1,0,0,0,0,0,0,-0.907378,-0.782984,1.0,...,0,0,0,0,0,0,0,0,0,0
2016-01-01,1,0,0,0,0,0,0,-0.885074,-0.837613,1.0,...,0,0,0,0,0,0,0,0,0,0
2016-01-01,1,0,0,0,0,0,0,-0.885074,-0.837613,1.0,...,0,0,0,0,0,0,0,0,0,0
2016-01-01,1,0,0,0,0,0,0,-1.453833,-1.493155,1.0,...,0,0,0,0,0,0,0,0,0,0
2016-01-01,1,0,0,0,0,0,0,-0.885074,-0.837613,1.0,...,0,0,0,0,0,0,0,0,0,0
2016-01-01,1,0,0,0,0,0,0,-0.951987,-0.870390,1.0,...,0,0,0,0,0,0,0,0,0,0
2016-01-01,1,0,0,0,0,0,0,-0.951987,-0.870390,1.0,...,0,0,0,0,0,0,0,0,0,0
2016-01-01,1,0,0,0,0,0,0,-1.844158,-2.137771,1.0,...,0,0,0,0,0,0,0,0,0,0
2016-01-01,1,0,0,0,0,0,0,-0.907378,-0.782984,1.0,...,0,0,0,0,0,0,0,0,0,0
2016-01-01,1,0,0,0,0,0,0,-0.907378,-0.782984,1.0,...,0,0,0,0,0,0,0,0,0,0
2016-01-01,1,0,0,0,0,0,0,-1.108117,-0.859464,1.0,...,1,0,0,0,0,0,0,0,0,0
2016-01-01,1,0,0,0,0,0,0,-0.873922,-0.914093,1.0,...,0,0,0,0,0,0,0,0,0,1
2016-01-01,1,0,0,0,0,0,0,-0.885074,-0.837613,1.0,...,0,0,0,0,0,0,0,0,0,0
2016-01-01,1,0,0,0,0,0,0,-0.885074,-0.837613,1.0,...,0,0,0,0,0,0,0,0,0,0
2016-01-01,1,0,0,0,0,0,0,-0.907378,-0.782984,1.0,...,0,0,0,0,0,0,0,0,0,0
2016-01-01,1,0,0,0,0,0,0,-0.885074,-0.837613,1.0,...,0,0,0,0,0,0,0,0,0,0
2016-01-01,1,0,0,0,0,0,0,-0.885074,-0.837613,1.0,...,0,0,0,0,0,0,0,0,0,0
2016-01-01,1,0,0,0,0,0,0,-0.907378,-0.782984,1.0,...,0,0,0,0,0,0,0,0,0,0
2016-01-01,1,0,0,0,0,0,0,-0.885074,-0.837613,1.0,...,0,0,0,0,0,0,0,0,0,0
2016-01-01,1,0,0,0,0,0,0,-0.873922,-0.914093,1.0,...,0,0,0,0,0,1,0,0,0,0
2016-01-01,1,0,0,0,0,0,0,-2.156418,-2.356285,1.0,...,0,0,0,0,0,0,0,0,0,0
2016-01-01,1,0,0,0,0,0,0,-0.951987,-0.870390,1.0,...,0,0,0,0,0,0,0,0,0,0
2016-01-01,1,0,0,0,0,0,0,-0.907378,-0.782984,1.0,...,0,0,0,0,0,0,0,0,0,0
2016-01-01,1,0,0,0,0,0,0,-0.885074,-0.837613,1.0,...,0,0,0,0,0,0,0,0,0,0
2016-01-01,1,0,0,0,0,0,0,-0.951987,-0.870390,1.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-02-28,0,0,0,0,0,1,0,-1.018899,-0.881316,0.0,...,0,0,0,0,0,0,0,0,0,1
2017-02-28,0,0,0,0,0,1,0,-1.186182,-0.772059,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-02-28,0,0,0,0,0,1,0,-1.253095,-1.077978,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-02-28,0,0,0,0,0,1,0,-1.108117,-1.056127,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-02-28,0,0,0,0,0,1,0,-0.751248,-0.564470,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-02-28,0,0,0,0,0,1,0,-0.885074,-0.706504,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-02-28,0,0,0,0,0,1,0,-1.108117,-1.056127,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-02-28,0,0,0,0,0,1,0,-1.108117,-1.056127,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-02-28,0,0,0,0,0,1,0,-0.751248,-0.564470,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-02-28,0,0,0,0,0,1,0,-1.108117,-1.056127,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-02-28,0,0,0,0,0,1,0,-0.751248,-0.564470,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-02-28,0,0,0,0,0,1,0,-0.751248,-0.564470,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-02-28,0,0,0,0,0,1,0,-1.108117,-1.056127,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-02-28,0,0,0,0,0,1,0,-1.108117,-1.056127,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-02-28,0,0,0,0,0,1,0,-1.253095,-1.077978,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-02-28,0,0,0,0,0,1,0,-1.108117,-1.056127,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-02-28,0,0,0,0,0,1,0,-1.108117,-1.056127,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-02-28,0,0,0,0,0,1,0,-0.751248,-0.564470,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-02-28,0,0,0,0,0,1,0,-0.751248,-0.564470,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-02-28,0,0,0,0,0,1,0,-1.598811,-1.427601,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-02-28,0,0,0,0,0,1,0,-1.108117,-1.056127,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-02-28,0,0,0,0,0,1,0,-1.018899,-0.881316,0.0,...,0,0,0,0,0,0,0,0,0,1
2017-02-28,0,0,0,0,0,1,0,-1.018899,-0.881316,0.0,...,0,0,0,0,0,0,0,0,0,1
2017-02-28,0,0,0,0,0,1,0,-2.122962,-1.930183,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-02-28,0,0,0,0,0,1,0,-0.751248,-0.564470,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-02-28,0,0,0,0,0,1,0,-0.840465,-0.739281,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-02-28,0,0,0,0,0,1,0,-1.108117,-1.056127,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-02-28,0,0,0,0,0,1,0,-1.108117,-1.056127,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-02-28,0,0,0,0,0,1,0,-0.751248,-0.564470,0.0,...,0,0,0,0,0,0,0,0,0,0
2017-02-28,0,0,0,0,0,1,0,-1.018899,-0.881316,0.0,...,0,0,0,0,0,0,0,0,1,0

In [ ]:
arima_exog["hours_sunlight1"]

In [195]:
arima_model = ARIMA(endog=arima_visitors_endo, order=(1,0,3), exog=np.array(arima_exog[["avg_temperature1", "high_temperature1", "holiday_flg", "low_temperature1", "hours_sunlight1"]]), dates=arima_dates, freq="D")          
# arima_model = ARIMA(endog=arima_visitors_endo, order=(1,0,3), dates=arima_dates, freq="D")

In [196]:
model_fit = arima_model.fit(start_params=None, trend="nc", method="mle", maxiter=10,\
               tol=1e-3,  transparams=True, disp=0)

/Users/derin/anaconda/lib/python3.6/site-packages/statsmodels/base/model.py:496: ConvergenceWarning:

Maximum Likelihood optimization failed to converge. Check mle_retvals

In [197]:
print (model_fit.summary())

                              ARMA Model Results
==============================================================================
Dep. Variable:                      y   No. Observations:               173703
Model:                     ARMA(1, 3)   Log Likelihood             -242782.733
Method:                           mle   S.D. of innovations              0.979
Date:                Wed, 18 Apr 2018   AIC                         485585.465
Time:                        15:47:14   BIC                         485686.116
Sample:                    01-01-2016   HQIC                        485615.272
                         - 02-28-2017
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.2688      0.051      5.307      0.000       0.170       0.368
x2            -0.2616      0.027     -9.538      0.000      -0.315      -0.208
x3             0.0566      0.027      2.134      0.033       0.005       0.109
x4             0.0255      0.029      0.865      0.387      -0.032       0.083
x5             0.0412      0.004     10.024      0.000       0.033       0.049
ar.L1.y        0.9963      0.000   2220.208      0.000       0.995       0.997
ma.L1.y       -0.9828      0.002   -393.753      0.000      -0.988      -0.978
ma.L2.y       -0.0050      0.003     -1.494      0.135      -0.012       0.002
ma.L3.y        0.0056      0.002      2.308      0.021       0.001       0.010
                                    Roots
=============================================================================
                 Real           Imaginary           Modulus         Frequency
-----------------------------------------------------------------------------
AR.1            1.0037           +0.0000j            1.0037            0.0000
MA.1            1.0181           +0.0000j            1.0181            0.0000
MA.2          -13.3465           +0.0000j           13.3465            0.5000
MA.3           13.2306           +0.0000j           13.2306            0.0000
-----------------------------------------------------------------------------

In [200]:
model_fit.params

array([ 0.26884425, -0.26160857,  0.05663674,  0.0255105 ,  0.04124935,
        0.99627644, -0.98284682, -0.00501825,  0.00556223])

In [209]:
data_test = data_test.set_index(data_test["visit_date"])

In [213]:
data_test.index = pd.Series(data_test.index.values).apply(lambda x: datetime.strptime(x, "%Y-%m-%d"))

In [216]:
data_test.index.values

array(['2017-03-01T00:00:00.000000000', '2017-03-03T00:00:00.000000000',
       '2017-03-04T00:00:00.000000000', ...,
       '2017-04-20T00:00:00.000000000', '2017-04-21T00:00:00.000000000',
       '2017-04-22T00:00:00.000000000'], dtype='datetime64[ns]')

In [227]:
model_fit.params

array([ 0.26884425, -0.26160857,  0.05663674,  0.0255105 ,  0.04124935,
        0.99627644, -0.98284682, -0.00501825,  0.00556223])

In [243]:
from statsmodels.tsa.arima_model import ARMAResults

In [246]:
params=model_fit.params

In [248]:
ARMAres = ARMAResults(arima_model, params=params)

In [253]:
len(data_train)

173703

In [269]:
ARMAres.predict(end=173703+30724, exog=np.array(data_test[["avg_temperature1", "high_temperature1", "holiday_flg", "low_temperature1", "hours_sunlight1"]]))[-30723:]

array([-1.18534417, -0.92905883, -0.30170453, ..., -0.38896434,
       -0.56235419, -0.70624204])

In [266]:
scaler.fit_transform(np.array(data_test["visitors"]).reshape(-1,1))

array([[-0.47512225],
       [-0.21328833],
       [-0.84168973],
       ...,
       [ 0.46747985],
       [ 0.78168055],
       [ 2.19558371]])

In [223]:
datetime.strptime("2017-03-01", "%Y-%m-%d").date()

datetime.date(2017, 3, 1)

In [239]:
model_fit.predict()

array([ 0.00390259,  0.06923672,  0.04725293, ..., -0.08116827,
       -0.07023863, -0.07935826])

In [242]:
arima_visitors_endo

array([[ 0.36549553],
       [ 0.78871241],
       [ 0.72825286],
       ...,
       [ 1.87698438],
       [-0.9041551 ],
       [ 1.27238884]])

In [275]:
area_names = data_train.columns.values[29:]

In [283]:
len(model_fit.params)

9

In [287]:
model_fit.predict(10)

array([ 0.05579593,  0.03637259,  0.07286226, ..., -0.08116827,
       -0.07023863, -0.07935826])

In [284]:
len(model_fit.predict())

173703

In [289]:
model_fit.predict(10)

array([ 0.05579593,  0.03637259,  0.07286226, ..., -0.08116827,
       -0.07023863, -0.07935826])

In [290]:
model_fit.params

array([ 0.96055674,  0.80359114,  0.81251241,  0.4198873 ,  0.06353344,
        0.03058221,  0.93515091,  0.66350827,  0.68371994])

131

In [295]:
model_fit.arparams

array([ 0.99627644])

In [296]:
model_fit.maparams

array([-0.98284682, -0.00501825,  0.00556223])